### ISSUE TITLE
App shows as version 2.8.2 after recent update to 2.8.3

### ISSUE THREAD

**Issue by phw** [flathub/org.musicbrainz.Picard#129] opened 2022-08-31 09:34 UTC
After the recent update for Picard 2.8.3 the app still shows as version 2.8.2 on [Flathub website](https://flathub.org/apps/details/org.musicbrainz.Picard).

After installing and launching the installed flatpak app it is indeed 2.8.3, but `flatpak info org.musicbrainz.Picard` also shows the version as 2.8.2.

AFAIK the version is pulled from the appstream data file, but that should be generated correctly by the build. I don't really see what changed since the last update to 2.8.2 that could have caused this.

**Comment by phw** [comment] 2022-08-31 09:44
I also tried the `pip install .` locally from the checked out 2.8.3 tag, and the package being build contains an appdata file with the new version. Is this a flathub / flatpak bug?

**Comment by Lctrs** [comment] 2022-08-31 11:27
Duplicate of #128. Problem is probably on flathub side then. I can't do anything on my side.

**Closed by Lctrs** 2022-08-31 11:27 UTC
